### ISSUE TITLE
Unguided Rockets on Star Wing

### ISSUE THREAD

**Issue by Benimus** [geordanr/xwing#509] opened 2017-10-23 22:49 UTC
Unguided Rockets on Alpha-class Star Wings don't save.

If you take an Alpha-class Star Wing, Nu Squadron Pilot with Os-1 Arsenal Loadout title, and equip Unguided Rockets, you get this link:

https://geordanr.github.io/xwing/?f=Galactic%20Empire&d=v4!s!270:-1,231:61:-1:U.-1,U.-1&sn=Unnamed%20Squadron&obs=

However, if you load that link again in another browser window, it changes to this:

https://geordanr.github.io/xwing/?f=Galactic%20Empire&d=v4!s!270:-1,-1:61:-1:U.-1,U.-1&sn=Unnamed%20Squadron&obs=

The 231 changes to a -1 and the ship no longer shows Unguided Rockets

**Comment by geordanr** [comment] 2017-10-23 23:27
The workaround is to put Unguided Rockets in the slot that was added by the Os-1 Arsenal Loadout: https://geordanr.github.io/xwing/?f=Galactic%20Empire&d=v4!s!270:-1,-1:61:-1:U.-1,U.231&sn=Unsaved%20Squadron&obs=

This is caused by the same bug in #506; marking this as a duplicate.

**Closed by geordanr** 2017-10-23 23:27 UTC
Labels: duplicate
