### ISSUE TITLE
Deleting Lists and Card Amounts

### ISSUE THREAD

**Issue by OFTHEHILLPEOPLE** [geordanr/xwing#253] opened 2015-10-23 18:00 UTC
Is there a way we could get a button or something in the Load Squad window so we can individually or mass delete squads in our list?  I have a ton of experimental lists that I need to delete and it's a pain to have to load them up and delete them individually.

Also, is there a way to show in the pull down tabs for upgrades how many cards we should have of a particular type of upgrade?  Like if I pull down the Elite Upgrade tab looking for Deadeye, can there be a bracket containing how many of that card we should own based on the sets we have?  I know it's in the back data so as to turn it red if we no longer have the available cards, but knowing how many I have would make choosing upgrades easier for swarm lists.

Thanks

**Comment by geordanr** [comment] 2015-10-27 01:19
Duplicate of #129 #219

**Closed by geordanr** 2015-10-27 01:19 UTC
Labels: duplicate
