### ISSUE TITLE
Your Collection

### ISSUE THREAD

**Issue by Wildhorn** [geordanr/xwing#293] opened 2016-02-25 19:51 UTC
Do you think it would be possible to manually add what we own? There is a huge community of selling and swapping individual ship/cards for X-Wing and would be nice to be able to really know if I can build a squad based on what I really own.

Example: I have 4 Autothruster, but doesnt own any Starviper ship.

**Comment by geordanr** [comment] 2016-02-25 20:15
Duplicate of #259

**Closed by geordanr** 2016-02-25 20:15 UTC
Labels: duplicate
