### ISSUE TITLE
Modification slot on Epic ships

### ISSUE THREAD

**Issue by Nehekharan** [geordanr/xwing#355] opened 2016-09-21 12:19 UTC
Hello,

I was creating a list for an upcoming Epic match but I encountered several issues when doing so in the squad builder:

- when adding a fore & aft section of a Raider to a squad both of the sections have a modification slot as in reality an epic ships can only have one (when you equip a mod to the for section, the mod slot of the aft section should dissappear/get disabled.
- when adding the 'Ordnance Tubes' mod to the for section I have the possiblity to add missiles/torpedoes in the hardpoint slot of the fore section, but the hardpoint slots on the aft section do not allow this.  (although this should be possible because the mod counts for the entire ship).

Thanks for you time & keep up the great work !
Michel

**Comment by geordanr** [comment] 2016-09-21 16:37
Duplicate of #342

**Closed by geordanr** 2016-09-21 16:37 UTC
Labels: duplicate
