### ISSUE TITLE
Maul on the B-wing

### ISSUE THREAD

**Issue by Retropenguin** [geordanr/xwing#559] opened 2018-02-13 10:55 UTC
Hi,

When I save my list that involves the crew 'Maul' in a B-wing (with ezra in the list in the sheathipeade shuttle), maul dissappears when I reload the list. 

The B/E2 upgrade doesn't dissappear, so that does not seem to be the issue. 
It's a minor thing, but I just wanted to report it

Cheers

**Comment by geordanr** [comment] 2018-02-13 19:08
This is a known issue; more details and a workaround are available at https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

Duplicate of #506

**Closed by geordanr** 2018-02-13 19:08 UTC
Labels: duplicate
