### ISSUE TITLE
Unable to keep Maul crew in list

### ISSUE THREAD

**Issue by JarvalF** [geordanr/xwing#530] opened 2017-12-08 09:48 UTC
Keyan Farlander has Maul crew equipped in [this list](https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!88:27,-1,-1,-1,-1:-1:11:U.250;277:18,75,2:-1:-1:;196:27,-1,3,254:39:15:&sn=Wave%2012%2F13%20Unboxing%20-%20Rebel%20(Robin)&obs=).

However, when you visit the link, Keyan does not have a crew equipped.

**Comment by JarvalF** [comment] 2017-12-08 09:51
This only appears to be affecting B-Wings with the B-Wing/E2 title equipped, as I've been able to equip Maul crew to Ezra's ship, or to other crew ships.

**Comment by zavrtak** [comment] 2017-12-08 11:18
https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!277:18,75,2:-1:-1:;196:27,-1,3,254:39:15:;88:27,-1,-1,-1,-1:-1:11:U.250&sn=Wave%2012%2F13%20Unboxing%20-%20Rebel%20(Robin)&obs=
Works fine for me. I am just kidding. ;-)

This is another case of how the sequencer work. It tries to equip Maul before the prerequisites for it are fulfilled and thus drops the upgrade.  If you first use Ezra have the ship with Maul following afterwards everything works fine. Hope this work around helps you. The bug itself is already known. Similar issues with ships with multiple crew slots or added slots and for example bomblet generator.

**Comment by geordanr** [comment] 2017-12-08 19:07
https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

Duplicate of #506

**Closed by geordanr** 2017-12-08 19:07 UTC
Labels: duplicate
