### ISSUE TITLE
'Your collection' section

### ISSUE THREAD

**Issue by radarronan** [geordanr/xwing#289] opened 2016-02-21 19:23 UTC
Hi,

Having been to a few tournaments now, I have picked up several alt art upgrade and pilot cards. I was wondering if it would be possible to have an option to add separate items to the 'my collection' section, so that they will show in the builder? 

Thanks!

**Comment by geordanr** [comment] 2016-02-23 01:54
Duplicate of #259

**Closed by geordanr** 2016-02-23 01:54 UTC
Labels: duplicate
