### ISSUE TITLE
Copying link with squad containing Maul does not work

### ISSUE THREAD

**Issue by JakobLanggaardNielsen** [geordanr/xwing#556] opened 2018-02-07 23:42 UTC
I have a Ghost/Fenn squad with Maul crew on the Ghost. When copying and pasting the link, Maul disappears.

Example: this squad originally did contain Maul, but the pasted link does not.

https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!158:44,135,-1,-1,250,165:25:3:;275:27,213,253:-1:-1:;162:-1,167:26:-1:&sn=Unnamed%20Squadron&obs=

**Comment by JakobLanggaardNielsen** [comment] 2018-02-07 23:45
https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!158:44,135,-1,-1,250,165:25:3:;275:27,213,253:-1:-1:;162:-1,167:26:-1:&sn=Unnamed%20Squadron&obs=

**Comment by geordanr** [comment] 2018-02-08 04:47
This is a known issue; more details and a workaround are available at https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

Duplicate of #506

**Closed by geordanr** 2018-02-08 04:47 UTC
Labels: duplicate
