### ISSUE TITLE
Feature Request: Option to Delete Squad from Squad List

### ISSUE THREAD

**Issue by jmheist** [geordanr/xwing#308] opened 2016-03-29 17:15 UTC
Really wanted to help out and add this in a branch for you, but I'm new to coffee and quickly got lost.

I use your site all the time, and have WAY to many squads (not all are winners). And I'd like to be able to quickly thin down my saved squad list, without having to open and delete them one by one.

Either a delete button next to each squad (by the load button?). Or a bulk edit, and have checkboxes next to each squad, and a delete all button to remove all selected.

Thanks for all your work on this project! It's easily becoming the defacto list building!

**Comment by geordanr** [comment] 2016-03-30 01:06
This is a popular one; I'll bump it in priority.

Duplicate of #129 (will be tracked there)

**Closed by geordanr** 2016-03-30 01:06 UTC
Labels: duplicate
