### ISSUE TITLE
Feature Request: Advanced Collection

### ISSUE THREAD

**Issue by Kumagoro42** [geordanr/xwing#292] opened 2016-02-24 05:12 UTC
This is by far my favorite X-Wing builder.
Only thing I'd like to see added is a way to directly add upgrade cards and pilots to your collection, not just expansion packs. People buy and trade cards outside of the packs. If we can't add them, we will be told a squad cannot be fielded when actually it can.
Thanks.

**Comment by geordanr** [comment] 2016-02-24 18:59
Duplicate of #259

**Closed by geordanr** 2016-02-24 18:59 UTC
Labels: duplicate
