### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by doramaar1937** [geordanr/xwing#584] opened 2018-06-25 18:20 UTC
## YASB Bug Report

Unable to Authenticate via Twitter. 

### Expected Behavior

I would expect to be authenticated and subsequently logged in to the site.

### Actual Behavior

When logging in via Twitter, I am brought to page: https://yasb-backend.herokuapp.com/auth/twitter
The only text on the page is: "Internal server error"  I am experiencing this issue across several networks on: a Windows laptop running Chrome, an iPhone running Safari, and another iPhone running Chrome. 

### Language

My apologies, but I don't know what this means.  Please let me know if I can provide any additional information to help address this issue.

  Thank you!

**Comment by geordanr** [comment] 2018-06-26 03:13
Duplicate of #582

**Closed by geordanr** 2018-06-26 03:13 UTC
Labels: duplicate

**Comment by doramaar1937** [comment] 2018-06-26 12:10
Thank you!
