### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RevBrowning** [geordanr/xwing#246] opened 2015-10-12 07:04 UTC
First, love the squad builder. Very clean interface, and incredibly easy to use. I was wondering if you had any intention of adding an indicator or changing the stat symbol on ships / pilots with non-standard primary weapons (e.g., 360 turrets, forward and rear facing guns like on the Firespray, etc.). The physical cards have this information represented by changing the icon for the Attack stat.

If you wanna be real fancy, there could also be a way to modify the icon (or whatever) in response to certain pieces of equipment, like the Outrider title (in a similar fashion to how equipping Twin Ion Engine Mk. II changes the maneuver template).

**Comment by geordanr** [comment] 2015-10-21 03:27
Duplicate of #157

**Closed by geordanr** 2015-10-21 03:27 UTC
