### ISSUE TITLE
Login Not Working 

### ISSUE THREAD

**Issue by RICoder72** [geordanr/xwing#426] opened 2017-03-23 17:16 UTC
When using the login button (note - I have never successfully logged into the site) I get "Internal Server Error" on the new window.

I have tried this with both Google and Facebook, in both Chrome and Edge browsers.

**Comment by geordanr** [comment] 2017-03-23 17:33
Duplicate of #424; please see my comments there requesting more information about this.

**Closed by geordanr** 2017-03-23 17:33 UTC
Labels: duplicate
