### ISSUE TITLE
An improvement

### ISSUE THREAD

**Issue by sh3u** [geordanr/xwing#395] opened 2017-01-27 10:29 UTC
Hi, first of all thank you for your effort and work. For me this is the best website for building squads and I use it daily.
I would like to suggest an improvement. I usually play X-Wing in TableTop Simulator and to load the squadron it needs to add the list in plain text, something like this:

Fenn Rau + Push the limit + Concord Dawn Protector + Autothrusters (34)
Fenn Rau + Veteran Instincts + Concord Dawn Protector + Autothrusters (30)

I have to use another web to generate the list this way but I would prefer it to be yours.
If you could add this functionality would be cool.

Thank you very much, greetings

**Comment by geordanr** [comment] 2017-01-27 19:20
Duplicate of #369

**Closed by geordanr** 2017-01-27 19:20 UTC
Labels: duplicate
